version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017

  db:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - app